site_name: Mindustry Wiki
site_url: https://mindustrygame.github.io/wiki/
repo_url: https://github.com/MindustryGame/wiki
docs_dir: 'docs_out'
theme: 
  name: material
  favicon: images/favicon.png
  logo: images/favicon.png
  custom_dir: overrides
  features:
    - navigation.tracking
extra_css:
  - 'stylesheets/style.css'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  features:
    - content.code.copy
